tap "homebrew/bundle"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
brew "neovim"
brew "python@3.9"
brew "rustup-init"
brew "ripgrep"
brew "bat"
brew "dasht"
brew "lolcat"
brew "fzf"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
