[[plugins]]
repo = "4513ECHO/vim-colors-hatsunemiku"

[[plugins]]
repo = "Rigellute/rigel"

[[plugins]]
repo = "lifepillar/vim-solarized8"

[[plugins]]
repo = "taDachs/kit.vim"

[[plugins]]
repo = "jacoborus/tender.vim"

[[plugins]]
repo = "morhetz/gruvbox"

[[plugins]]
repo = "KeitaNakamura/neodark.vim"

[[plugins]]
repo = "bluz71/vim-nightfly-guicolors"
